### Create a new report

POST http://localhost:3000/reports
Content-Type: application/json

{
	"mileage": 135000,
	
	"price": 8000,

	"make": "Citröen",

	"model": "C4",

	"year": 2010,

	"lng": 6.351160,

	"lat": 48.198850
}

### Approve an existing report
PATCH http://localhost:3000/reports/5
Content-Type: application/json

{
	"approved": true
}

### Get an estimate for an existing vehicule
GET http://localhost:3000/reports?make=Citröen&model=c4&lng=6.351160&lat=48.198850&mileage=135000&year=2010