### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
	"email": "bobthedog1@dogg.com",
	"password": "dogg"
}

### Find an user with a particular ID

GET http://localhost:3000/auth/3

### Find all user with a given email

GET http://localhost:3000/auth?email=bobthedog@dogg.com

### Delete a user with given ID

DELETE  http://localhost:3000/auth/1

### Update a user

PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
	"email": "snoopTheDog@dogg.com",
	"password": "don'tTestTheDogg"
}